<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">

<table style="box-sizing: border-box; border-spacing: 0px; border-collapse: collapse; margin-top: 0px; margin-bottom: 16px; display: block; width: max-content; max-width: 100%; overflow: auto; font-variant: tabular-nums; color: rgb(240, 246, 252); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
	<thead style="box-sizing: border-box;">
		<tr style="box-sizing: border-box; background-color: rgb(13, 17, 23); border-top: 1px solid rgba(61, 68, 77, 0.7);">
			<th style="box-sizing: border-box; padding: 6px 13px; font-weight: 600; border-color: rgb(61, 68, 77); border-style: solid; border-width: 1px; border-image: none 100% / 1 / 0 stretch;">
			Architecture</th>
			<th style="box-sizing: border-box; padding: 6px 13px; font-weight: 600; border-color: rgb(61, 68, 77); border-style: solid; border-width: 1px; border-image: none 100% / 1 / 0 stretch;">
			Windows</th>
			<th style="box-sizing: border-box; padding: 6px 13px; font-weight: 600; border-color: rgb(61, 68, 77); border-style: solid; border-width: 1px; border-image: none 100% / 1 / 0 stretch;">
			Ubuntu</th>
			<th style="box-sizing: border-box; padding: 6px 13px; font-weight: 600; border-color: rgb(61, 68, 77); border-style: solid; border-width: 1px; border-image: none 100% / 1 / 0 stretch;">
			Mac</th>
			<th style="box-sizing: border-box; padding: 6px 13px; font-weight: 600; border-color: rgb(61, 68, 77); border-style: solid; border-width: 1px; border-image: none 100% / 1 / 0 stretch;">
			Android</th>
			<th style="box-sizing: border-box; padding: 6px 13px; font-weight: 600; border-color: rgb(61, 68, 77); border-style: solid; border-width: 1px; border-image: none 100% / 1 / 0 stretch;">
			Flatpak</th>
			<th style="box-sizing: border-box; padding: 6px 13px; font-weight: 600; border-color: rgb(61, 68, 77); border-style: solid; border-width: 1px; border-image: none 100% / 1 / 0 stretch;">
			iOS</th>
			<th style="box-sizing: border-box; padding: 6px 13px; font-weight: 600; border-color: rgb(61, 68, 77); border-style: solid; border-width: 1px; border-image: none 100% / 1 / 0 stretch;">
			Web</th>
		</tr>
	</thead>
	<tbody style="box-sizing: border-box;">
		<tr style="box-sizing: border-box; background-color: rgb(13, 17, 23); border-top: 1px solid rgba(61, 68, 77, 0.7);">
			<td style="box-sizing: border-box; padding: 6px 13px; border-color: rgb(61, 68, 77); border-style: solid; border-width: 1px; border-image: none 100% / 1 / 0 stretch;">
			x86-64 (64-bit)</td>
			<td style="box-sizing: border-box; padding: 6px 13px; border-color: rgb(61, 68, 77); border-style: solid; border-width: 1px; border-image: none 100% / 1 / 0 stretch;">
			<a style="box-sizing: border-box; background-color: transparent; color: rgb(68, 147, 248); text-decoration: underline; text-underline-offset: 0.2rem;" href="https://github.com/rustdesk/rustdesk/releases/download/1.4.0/rustdesk-1.4.0-x86_64.exe">
			EXE</a><span>&nbsp;</span>&nbsp;<span>&nbsp;</span><a style="box-sizing: border-box; background-color: transparent; color: rgb(68, 147, 248); text-decoration: underline; text-underline-offset: 0.2rem; margin-bottom: 0px;" href="https://github.com/rustdesk/rustdesk/releases/download/1.4.0/rustdesk-1.4.0-x86_64.msi">MSI</a></td>
			<td style="box-sizing: border-box; padding: 6px 13px; border-color: rgb(61, 68, 77); border-style: solid; border-width: 1px; border-image: none 100% / 1 / 0 stretch;">
			<a style="box-sizing: border-box; background-color: transparent; color: rgb(68, 147, 248); text-decoration: underline; text-underline-offset: 0.2rem; margin-bottom: 0px;" href="https://github.com/rustdesk/rustdesk/releases/download/1.4.0/rustdesk-1.4.0-x86_64.deb">
			Download</a></td>
			<td style="box-sizing: border-box; padding: 6px 13px; border-color: rgb(61, 68, 77); border-style: solid; border-width: 1px; border-image: none 100% / 1 / 0 stretch;">
			<a style="box-sizing: border-box; background-color: transparent; color: rgb(68, 147, 248); text-decoration: underline; text-underline-offset: 0.2rem; margin-bottom: 0px;" href="https://github.com/rustdesk/rustdesk/releases/download/1.4.0/rustdesk-1.4.0-x86_64.dmg">
			Download</a></td>
			<td style="box-sizing: border-box; padding: 6px 13px; border-color: rgb(61, 68, 77); border-style: solid; border-width: 1px; border-image: none 100% / 1 / 0 stretch;">
			<a style="box-sizing: border-box; background-color: transparent; color: rgb(68, 147, 248); text-decoration: underline; text-underline-offset: 0.2rem; margin-bottom: 0px;" href="https://github.com/rustdesk/rustdesk/releases/download/1.4.0/rustdesk-1.4.0-universal-signed.apk">
			Universal</a></td>
			<td style="box-sizing: border-box; padding: 6px 13px; border-color: rgb(61, 68, 77); border-style: solid; border-width: 1px; border-image: none 100% / 1 / 0 stretch;">
			<a style="box-sizing: border-box; background-color: transparent; color: rgb(68, 147, 248); text-decoration: underline; text-underline-offset: 0.2rem; margin-bottom: 0px;" href="https://github.com/rustdesk/rustdesk/releases/download/1.4.0/rustdesk-1.4.0-x86_64.flatpak">
			Download</a></td>
			<td style="box-sizing: border-box; padding: 6px 13px; border-color: rgb(61, 68, 77); border-style: solid; border-width: 1px; border-image: none 100% / 1 / 0 stretch;">
			</td>
			<td style="box-sizing: border-box; padding: 6px 13px; border-color: rgb(61, 68, 77); border-style: solid; border-width: 1px; border-image: none 100% / 1 / 0 stretch;">
			<a rel="nofollow" style="box-sizing: border-box; background-color: transparent; color: rgb(68, 147, 248); text-decoration: underline; text-underline-offset: 0.2rem; margin-bottom: 0px;" href="https://rustdesk.com/web">
			Go</a></td>
		</tr>
		<tr style="box-sizing: border-box; background-color: rgb(21, 27, 35); border-top: 1px solid rgba(61, 68, 77, 0.7);">
			<td style="box-sizing: border-box; padding: 6px 13px; border-color: rgb(61, 68, 77); border-style: solid; border-width: 1px; border-image: none 100% / 1 / 0 stretch;">
			AArch64 (ARM64)</td>
			<td style="box-sizing: border-box; padding: 6px 13px; border-color: rgb(61, 68, 77); border-style: solid; border-width: 1px; border-image: none 100% / 1 / 0 stretch;">
			</td>
			<td style="box-sizing: border-box; padding: 6px 13px; border-color: rgb(61, 68, 77); border-style: solid; border-width: 1px; border-image: none 100% / 1 / 0 stretch;">
			<a style="box-sizing: border-box; background-color: transparent; color: rgb(68, 147, 248); text-decoration: underline; text-underline-offset: 0.2rem; margin-bottom: 0px;" href="https://github.com/rustdesk/rustdesk/releases/download/1.4.0/rustdesk-1.4.0-aarch64.deb">
			Download</a></td>
			<td style="box-sizing: border-box; padding: 6px 13px; border-color: rgb(61, 68, 77); border-style: solid; border-width: 1px; border-image: none 100% / 1 / 0 stretch;">
			<a style="box-sizing: border-box; background-color: transparent; color: rgb(68, 147, 248); text-decoration: underline; text-underline-offset: 0.2rem; margin-bottom: 0px;" href="https://github.com/rustdesk/rustdesk/releases/download/1.4.0/rustdesk-1.4.0-aarch64.dmg">
			Download</a></td>
			<td style="box-sizing: border-box; padding: 6px 13px; border-color: rgb(61, 68, 77); border-style: solid; border-width: 1px; border-image: none 100% / 1 / 0 stretch;">
			<a style="box-sizing: border-box; background-color: transparent; color: rgb(68, 147, 248); text-decoration: underline; text-underline-offset: 0.2rem; margin-bottom: 0px;" href="https://github.com/rustdesk/rustdesk/releases/download/1.4.0/rustdesk-1.4.0-aarch64-signed.apk">
			Download</a></td>
			<td style="box-sizing: border-box; padding: 6px 13px; border-color: rgb(61, 68, 77); border-style: solid; border-width: 1px; border-image: none 100% / 1 / 0 stretch;">
			<a style="box-sizing: border-box; background-color: transparent; color: rgb(68, 147, 248); text-decoration: underline; text-underline-offset: 0.2rem; margin-bottom: 0px;" href="https://github.com/rustdesk/rustdesk/releases/download/1.4.0/rustdesk-1.4.0-aarch64.flatpak">
			Download</a></td>
			<td style="box-sizing: border-box; padding: 6px 13px; border-color: rgb(61, 68, 77); border-style: solid; border-width: 1px; border-image: none 100% / 1 / 0 stretch;">
			<a rel="nofollow" style="box-sizing: border-box; background-color: transparent; color: rgb(68, 147, 248); text-decoration: underline; text-underline-offset: 0.2rem; margin-bottom: 0px;" href="https://apps.apple.com/us/app/rustdesk-remote-desktop/id1581225015">
			App Store</a></td>
			<td style="box-sizing: border-box; padding: 6px 13px; border-color: rgb(61, 68, 77); border-style: solid; border-width: 1px; border-image: none 100% / 1 / 0 stretch;">
			</td>
		</tr>
		<tr style="box-sizing: border-box; background-color: rgb(13, 17, 23); border-top: 1px solid rgba(61, 68, 77, 0.7);">
			<td style="box-sizing: border-box; padding: 6px 13px; border-color: rgb(61, 68, 77); border-style: solid; border-width: 1px; border-image: none 100% / 1 / 0 stretch;">
			ARMv7 (32-bit)</td>
			<td style="box-sizing: border-box; padding: 6px 13px; border-color: rgb(61, 68, 77); border-style: solid; border-width: 1px; border-image: none 100% / 1 / 0 stretch;">
			</td>
			<td style="box-sizing: border-box; padding: 6px 13px; border-color: rgb(61, 68, 77); border-style: solid; border-width: 1px; border-image: none 100% / 1 / 0 stretch;">
			<a style="box-sizing: border-box; background-color: transparent; color: rgb(68, 147, 248); text-decoration: underline; text-underline-offset: 0.2rem; margin-bottom: 0px;" href="https://github.com/rustdesk/rustdesk/releases/download/1.4.0/rustdesk-1.4.0-armv7-sciter.deb">
			Download</a></td>
			<td style="box-sizing: border-box; padding: 6px 13px; border-color: rgb(61, 68, 77); border-style: solid; border-width: 1px; border-image: none 100% / 1 / 0 stretch;">
			</td>
			<td style="box-sizing: border-box; padding: 6px 13px; border-color: rgb(61, 68, 77); border-style: solid; border-width: 1px; border-image: none 100% / 1 / 0 stretch;">
			<a style="box-sizing: border-box; background-color: transparent; color: rgb(68, 147, 248); text-decoration: underline; text-underline-offset: 0.2rem; margin-bottom: 0px;" href="https://github.com/rustdesk/rustdesk/releases/download/1.4.0/rustdesk-1.4.0-armv7-signed.apk">
			Download</a></td>
			<td style="box-sizing: border-box; padding: 6px 13px; border-color: rgb(61, 68, 77); border-style: solid; border-width: 1px; border-image: none 100% / 1 / 0 stretch;">
			</td>
			<td style="box-sizing: border-box; padding: 6px 13px; border-color: rgb(61, 68, 77); border-style: solid; border-width: 1px; border-image: none 100% / 1 / 0 stretch;">
			</td>
			<td style="box-sizing: border-box; padding: 6px 13px; border-color: rgb(61, 68, 77); border-style: solid; border-width: 1px; border-image: none 100% / 1 / 0 stretch;">
			</td>
		</tr>
		<tr style="box-sizing: border-box; background-color: rgb(21, 27, 35); border-top: 1px solid rgba(61, 68, 77, 0.7);">
			<td style="box-sizing: border-box; padding: 6px 13px; border-color: rgb(61, 68, 77); border-style: solid; border-width: 1px; border-image: none 100% / 1 / 0 stretch;">
			x86-32 (32-bit)</td>
			<td style="box-sizing: border-box; padding: 6px 13px; border-color: rgb(61, 68, 77); border-style: solid; border-width: 1px; border-image: none 100% / 1 / 0 stretch;">
			<a style="box-sizing: border-box; background-color: transparent; color: rgb(68, 147, 248); text-decoration: underline; text-underline-offset: 0.2rem; margin-bottom: 0px;" href="https://github.com/rustdesk/rustdesk/releases/download/1.4.0/rustdesk-1.4.0-x86-sciter.exe">
			EXE</a></td>
			<td style="box-sizing: border-box; padding: 6px 13px; border-color: rgb(61, 68, 77); border-style: solid; border-width: 1px; border-image: none 100% / 1 / 0 stretch;">
			</td>
			<td style="box-sizing: border-box; padding: 6px 13px; border-color: rgb(61, 68, 77); border-style: solid; border-width: 1px; border-image: none 100% / 1 / 0 stretch;">
			</td>
			<td style="box-sizing: border-box; padding: 6px 13px; border-color: rgb(61, 68, 77); border-style: solid; border-width: 1px; border-image: none 100% / 1 / 0 stretch;">
			</td>
			<td style="box-sizing: border-box; padding: 6px 13px; border-color: rgb(61, 68, 77); border-style: solid; border-width: 1px; border-image: none 100% / 1 / 0 stretch;">
			</td>
			<td style="box-sizing: border-box; padding: 6px 13px; border-color: rgb(61, 68, 77); border-style: solid; border-width: 1px; border-image: none 100% / 1 / 0 stretch;">
			</td>
			<td style="box-sizing: border-box; padding: 6px 13px; border-color: rgb(61, 68, 77); border-style: solid; border-width: 1px; border-image: none 100% / 1 / 0 stretch;">
			</td>
		</tr>
</table>
<br class="Apple-interchange-newline">
